// Generated by CoffeeScript 2.7.0
(function() {
  var L;

  L = Lightue;

  L({
    name: {
      $tag: 'h1',
      $$: 'Smalllong'
    },
    details: [
      'experienced frontend developer located in Shanghai',
      {
        $$: 'github:',
        link: L.a({
          _href: 'https://github.com/smalllong',
          $$: 'https://github.com/smalllong'
        })
      },
      {
        $$: 'email:',
        link: L.a({
          _href: 'mailto:m18818276304@icloud.com',
          $$: 'm18818276304@icloud.com'
        })
      }
    ]
  });

}).call(this);
