// Generated by CoffeeScript 2.7.0
(function() {
  var S;

  S = Lightue.useState({
    now: new Date(),
    rootTop: Math.floor(Math.random() * (window.innerHeight - 120))
  });

  Lightue({
    _style: () => {
      return 'top: ' + S.rootTop + 'px';
    },
    time: () => {
      return S.now.toLocaleTimeString();
    },
    date: () => {
      return S.now.toLocaleDateString();
    }
  });

  window.onresize = () => {
    return S.rootTop = Math.floor(Math.random() * (window.innerHeight - 120));
  };

  setInterval(() => {
    S.now = new Date();
    if (S.now.getSeconds() === 0) {
      return window.onresize();
    }
  }, 1000);

}).call(this);
